
import type { Project, TeamMember, Vendor, BudgetCategory, Task, RFI, Issue, BudgetItem, Expense, ChangeOrder } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const teamMembers: TeamMember[] = [
  { id: 'user-1', name: 'Alice Johnson', role: 'Project Manager', email: 'alice@constructai.com', phone: '111-222-3333', avatarUrl: 'https://i.pravatar.cc/150?u=alice' },
  { id: 'user-2', name: 'Bob Williams', role: 'Site Superintendent', email: 'bob@constructai.com', phone: '444-555-6666', avatarUrl: 'https://i.pravatar.cc/150?u=bob' },
  { id: 'user-3', name: 'Charlie Brown', role: 'Estimator', email: 'charlie@constructai.com', phone: '777-888-9999', avatarUrl: 'https://i.pravatar.cc/150?u=charlie' },
];

export const vendors: Vendor[] = [
  { id: 'vendor-1', name: 'A & G Electric', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Electrical' },
  { id: 'vendor-2', name: 'A Morfin Trucking LLC', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Trucking' },
  { id: 'vendor-3', name: 'ACT PIPE AND SUPPLY, INC.', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Piping' },
  { id: 'vendor-4', name: 'Action Gypsum', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Drywall' },
  { id: 'vendor-5', name: 'Advanced LED Solution', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Electrical' },
  { id: 'vendor-6', name: 'Alexanders Construction', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Construction' },
  { id: 'vendor-7', name: 'Alif Security LLC', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Security' },
  { id: 'vendor-8', name: 'Allied Hydromulch TX, LLC', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Landscaping' },
  { id: 'vendor-9', name: 'Amazon', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Supplier' },
  { id: 'vendor-10', name: 'Andrade Construction (Sandra Cruz)', contactPerson: 'Sandra Cruz', phone: 'N/A', email: 'N/A', trade: 'General Construction' },
  { id: 'vendor-11', name: 'Arise Furniture LLC', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Furniture' },
  { id: 'vendor-12', name: 'Backflow Technicians', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Plumbing' },
  { id: 'vendor-13', name: 'Barreras Glass', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Glazing' },
  { id: 'vendor-14', name: 'Brent Lowrey', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Contractor' },
  { id: 'vendor-15', name: 'Camarillo Trucks', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Trucking' },
  { id: 'vendor-16', name: 'Cano', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-17', name: 'Carlos Osorto', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Steel' },
  { id: 'vendor-18', name: 'CNA SURETY', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Insurance' },
  { id: 'vendor-19', name: 'Compania Vision', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-20', name: 'Concrete Cleaning Inc. (Polished Concrete)', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Concrete' },
  { id: 'vendor-21', name: 'Crow Castle LLC', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Construction' },
  { id: 'vendor-22', name: 'CUSTOM BUILDS & RENTALS, LLC', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Rental' },
  { id: 'vendor-23', name: 'Dumpster Dogs TX', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Waste Management' },
  { id: 'vendor-24', name: 'Dynamic Fastener', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Supplier' },
  { id: 'vendor-25', name: 'ECUA Homes (Sand+Stabulizer)', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Sitework' },
  { id: 'vendor-26', name: 'Eloy Torres', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-27', name: 'Enrique Arteaga', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-28', name: 'Equadors Trucking Services', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Trucking' },
  { id: 'vendor-29', name: 'Fabco', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Supplier' },
  { id: 'vendor-30', name: 'Final Inspection 11/4/2024', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Inspection' },
  { id: 'vendor-31', name: 'Fire Sprinkler System', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Fire Protection' },
  { id: 'vendor-32', name: 'Fire Sprinkler Texas', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Fire Protection' },
  { id: 'vendor-33', name: 'Floor & Decor', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Flooring' },
  { id: 'vendor-34', name: 'Frank Gonzalez', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-35', name: 'Gabriel Pena', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-36', name: 'GC Rebar', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Concrete' },
  { id: 'vendor-37', name: 'Glavatec Inc.', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Technology' },
  { id: 'vendor-38', name: 'GM Commercial Services', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Commercial Services' },
  { id: 'vendor-39', name: 'Gomez MGS (Moises Gomez)', contactPerson: 'Moises Gomez', phone: 'N/A', email: 'N/A', trade: 'General Construction' },
  { id: 'vendor-40', name: 'Grainger', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Supplier' },
  { id: 'vendor-41', name: 'H2ECO Bulk LLC', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Supplier' },
  { id: 'vendor-42', name: 'HC Empire Drywall', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Drywall' },
  { id: 'vendor-43', name: 'Henry Osorto', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-44', name: 'Home Depot', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Supplier' },
  { id: 'vendor-45', name: 'Hunton AC Units Trane', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'HVAC' },
  { id: 'vendor-46', name: 'Israel Figueroa', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-47', name: 'Jacore Fire Protection Co.', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Fire Protection' },
  { id: 'vendor-48', name: 'Jorge De Los Santos', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-49', name: 'Jose Ramirez', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-50', name: 'Juan F. Harnandez', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-51', name: 'Juan Molina', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-52', name: 'Juan Valadez', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-53', name: 'KES Landscaping LLC', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Landscaping' },
  { id: 'vendor-54', name: 'L & G Equipment Rentals Inc.', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Rental' },
  { id: 'vendor-55', name: 'Leon Plumbing', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Plumbing' },
  { id: 'vendor-56', name: 'Lone Star Mapping LLC', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Surveying' },
  { id: 'vendor-57', name: 'Longhorn Texas Supply', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Supplier' },
  { id: 'vendor-58', name: 'LP Drilling, Texas City', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Drilling' },
  { id: 'vendor-59', name: 'Makmo Design LLC', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Design' },
  { id: 'vendor-60', name: 'MBCI', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Supplier' },
  { id: 'vendor-61', name: 'Norris Mechanical Services & More', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Mechanical' },
  { id: 'vendor-62', name: 'Point Equipment Rental', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Rental' },
  { id: 'vendor-63', name: 'Precision Concrete Pumping LLC', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Concrete' },
  { id: 'vendor-64', name: 'Pye Barker Fire & Safety', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Fire Protection' },
  { id: 'vendor-65', name: 'Quality Tles', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Flooring' },
  { id: 'vendor-66', name: 'Quick Waste', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Waste Management' },
  { id: 'vendor-67', name: 'Red River Storm Water', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Sitework' },
  { id: 'vendor-68', name: 'Revels Brick Company Inc.', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Masonry' },
  { id: 'vendor-69', name: 'Reynaldo Benitez', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-70', name: 'Ricardo Rodriguez', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-71', name: 'Rodolfo Ladesma', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-72', name: 'Rodrigos Concrete Cuts & Cores', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Concrete' },
  { id: 'vendor-73', name: 'Roto Rooter', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Plumbing' },
  { id: 'vendor-74', name: "Sam's Club", contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Supplier' },
  { id: 'vendor-75', name: 'Sandra Cruz', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-76', name: 'Sapo Engineering', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Engineering' },
  { id: 'vendor-77', name: 'Sherwin Williams', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Painting' },
  { id: 'vendor-78', name: 'South Houston Concrete Pipe Co.', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Concrete' },
  { id: 'vendor-79', name: 'Stainless Kitchen & More', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Kitchen' },
  { id: 'vendor-80', name: 'Strifes Air Conditioning & Heating', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'HVAC' },
  { id: 'vendor-81', name: 'Sylvia Valadez', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-82', name: 'Tejas Materials, Inc.', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Supplier' },
  { id: 'vendor-83', name: 'Texas Contracting Consultants', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Consulting' },
  { id: 'vendor-84', name: 'Texas Shield Roofing LLC', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Roofing' },
  { id: 'vendor-85', name: 'Texcon Ready Mix Inc.', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Concrete' },
  { id: 'vendor-86', name: 'The Kings Transport', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Trucking' },
  { id: 'vendor-87', name: 'The Murillo Company', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Construction' },
  { id: 'vendor-88', name: 'TO BE PAID', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Accounting' },
  { id: 'vendor-89', name: 'Triple S', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Supplier' },
  { id: 'vendor-90', name: 'Tulio Linares', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
  { id: 'vendor-91', name: 'Uinted Rentals', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'Rental' },
  { id: 'vendor-92', name: 'Victor Rodriguez', contactPerson: 'N/A', phone: 'N/A', email: 'N/A', trade: 'General Labor' },
];

export const budgetCategories: BudgetCategory[] = [
  { id: 'cat-1', name: 'Demolition' },
  { id: 'cat-2', name: 'Concrete' },
  { id: 'cat-3', name: 'Masonry' },
  { id: 'cat-4', name: 'Steel' },
  { id: 'cat-5', name: 'Framing' },
  { id: 'cat-6', name: 'Plumbing' },
  { id: 'cat-7', name: 'Electrical' },
  { id: 'cat-8', name: 'HVAC' },
  { id: 'cat-9', name: 'Finishes' },
  { id: 'cat-10', name: 'Site Work' },
  { id: 'cat-11', name: 'Ansul System' },
  { id: 'cat-12', name: 'Bathroom Partitions' },
  { id: 'cat-13', name: 'Bollards/Stoppers' },
  { id: 'cat-14', name: 'Change Order' },
  { id: 'cat-15', name: 'Cleaning' },
  { id: 'cat-16', name: 'CMU' },
  { id: 'cat-17', name: 'Doors/Hardware' },
  { id: 'cat-18', name: 'Exterior panels' },
  { id: 'cat-19', name: 'Fences' },
  { id: 'cat-20', name: 'Floor' },
  { id: 'cat-21', name: 'Foundation Labor' },
  { id: 'cat-22', name: 'Foundation Material' },
  { id: 'cat-23', name: 'Foundation-Piers Labor' },
  { id: 'cat-24', name: 'Framing Labor' },
  { id: 'cat-25', name: 'Framing Material' },
  { id: 'cat-26', name: 'Fuel Canopy Labor' },
  { id: 'cat-27', name: 'Fuel Canopy Material' },
  { id: 'cat-28', name: 'FuelCanopyBricks' },
  { id: 'cat-29', name: 'Get Reimbursed' },
  { id: 'cat-30', name: 'Grass Cut' },
  { id: 'cat-31', name: 'Haul-Off' },
  { id: 'cat-32', name: 'KnoxBox' },
  { id: 'cat-33', name: 'Landsacpe Labor' },
  { id: 'cat-34', name: 'Landsacpe Material' },
  { id: 'cat-35', name: 'Millwork' },
  { id: 'cat-36', name: 'Misc' },
  { id: 'cat-37', name: 'Nichiha Labor' },
  { id: 'cat-38', name: 'Nichiha Material' },
  { id: 'cat-39', name: 'Paint Labor' },
  { id: 'cat-40', name: 'Paint Material' },
  { id: 'cat-41', name: 'Parking lot Labor' },
  { id: 'cat-42', name: 'Parking lot Material' },
  { id: 'cat-43', name: 'Permit' },
  { id: 'cat-44', name: 'Pollution Control' },
  { id: 'cat-45', name: 'Rental' },
  { id: 'cat-46', name: 'Roof' },
  { id: 'cat-47', name: 'Sitework Labor' },
  { id: 'cat-48', name: 'Sitework Material' },
  { id: 'cat-49', name: 'Steel Labor' },
  { id: 'cat-50', name: 'Steel Material' },
  { id: 'cat-51', name: 'StoreFrontCanopy Labor' },
  { id: 'cat-52', name: 'StoreFrontCanopy Material' },
  { id: 'cat-53', name: 'Store Front Glass' },
  { id: 'cat-54', name: 'Striping' },
  { id: 'cat-55', name: 'Stucco/Stone' },
  { id: 'cat-56', name: 'Survey' },
  { id: 'cat-57', name: 'SWPP' },
  { id: 'cat-58', name: 'Tiles Labor' },
  { id: 'cat-59', name: 'Tiles Material' },
  { id: 'cat-60', name: 'TO BE PAID' },
  { id: 'cat-61', name: 'Undrgrnd pipes Labor' },
  { id: 'cat-62', name: 'Undrgrnd pipes Material' },
  { id: 'cat-63', 'name': 'Utility Bill' },
  { id: 'cat-64', name: 'Venthood' },
  { id: 'cat-65', name: 'Builders Risk' },
  { id: 'cat-66', name: 'Curbs Labor' },
  { id: 'cat-67', name: 'Curbs Material' },
  { id: 'cat-68', name: 'Sitework Material' },
  { id: 'cat-69', name: 'Sidewalk Labor' },
  { id: 'cat-70', name: 'Sidewalk Material' },
  { id: 'cat-71', name: 'Dirtwork-Lbr' },
  { id: 'cat-72', name: '.GROUNDBREAK' },
  { id: 'cat-73', name: 'Haul Off' },
  { id: 'cat-74', name: 'Foundation-Main' },
  { id: 'cat-75', name: 'Foundation-Mtrl' },
  { id: 'cat-76', name: 'Parking lot-Mtrl' },
  { id: 'cat-77', name: 'Parking lot-Labor' },
];

export const projects: Project[] = [
  {
    id: 'proj-1',
    projectNumber: '2023-001',
    name: 'Downtown Office Tower',
    ownerName: 'Metropolis Holdings',
    addressStreet: '123 Commerce St',
    city: 'New York',
    zip: '10001',
    description: 'A 50-story office building with retail space on the ground floor.',
    status: 'In Progress',
    percentComplete: 45,
    startDate: '2023-01-15',
    endDate: '2025-12-31',
    revisedContract: 150000000,
    finalBidAmount: 165000000,
    imageUrl: 'https://picsum.photos/seed/tower/600/400',
    imageHint: 'office tower',
  },
  {
    id: 'proj-2',
    projectNumber: '2023-002',
    name: 'Suburban Retail Center',
    ownerName: 'Community Builders',
    addressStreet: '456 Retail Ave',
    city: 'Anytown',
    zip: '54321',
    description: 'A sprawling retail center with multiple tenants.',
    status: 'Planning',
    percentComplete: 10,
    startDate: '2023-06-01',
    endDate: '2024-08-31',
    revisedContract: 25000000,
    finalBidAmount: 27500000,
    imageUrl: 'https://picsum.photos/seed/retail/600/400',
    imageHint: 'retail center',
  },
  {
    id: 'proj-3',
    projectNumber: '2023-003',
    name: 'Hillside Residence',
    ownerName: 'The Smith Family',
    addressStreet: '789 Vista Dr',
    city: 'Beverly Hills',
    zip: '90210',
    description: 'A luxury single-family home with a pool and guest house.',
    status: 'Completed',
    percentComplete: 100,
    startDate: '2022-03-01',
    endDate: '2023-09-15',
    revisedContract: 5000000,
    finalBidAmount: 5500000,
    imageUrl: 'https://picsum.photos/seed/residence/600/400',
    imageHint: 'luxury home',
  },
  {
    id: 'proj-4',
    projectNumber: '8845',
    name: 'Temple 8845',
    ownerName: 'Temple 8845 Owner',
    addressStreet: 'Temple 8845 Address',
    city: 'Temple',
    zip: '76502',
    description: 'Temple 8845 Project',
    status: 'In Progress',
    percentComplete: 50,
    startDate: '2025-08-12',
    endDate: '2026-08-12',
    revisedContract: 500000,
    finalBidAmount: 550000,
    imageUrl: 'https://picsum.photos/seed/temple/600/400',
    imageHint: 'construction site',
  }
];

export const tasks: Task[] = [
  { id: 'task-1', projectId: 'proj-1', title: 'Finalize structural steel drawings', status: 'In Progress', priority: 'High', assigneeId: 'user-1', dueDate: '2024-07-30' },
  { id: 'task-2', projectId: 'proj-1', title: 'Procure curtain wall materials', status: 'To Do', priority: 'Medium', assigneeId: 'user-2', dueDate: '2024-08-15' },
  { id: 'task-3', projectId: 'proj-2', title: 'Submit for zoning variance', status: 'Done', priority: 'High', assigneeId: 'user-1', dueDate: '2024-05-20' },
  { id: 'task-4', projectId: 'proj-3', title: 'Complete final punch list', status: 'Done', priority: 'Low', assigneeId: 'user-2', dueDate: '2023-09-01' },
  { id: 'task-5', projectId: 'proj-1', title: 'Install HVAC units on floors 10-15', status: 'To Do', priority: 'Medium', assigneeId: 'user-2', dueDate: '2024-08-05' },
];

export const rfis: RFI[] = [
  { id: 'rfi-1', projectId: 'proj-1', rfiNumber: 'RFI-001', dateSubmitted: '2024-07-20', subject: 'Clarification on beam connection detail', question: 'Drawing S-501 shows a bolted connection, but S-502 shows a welded connection for the same beam type. Please clarify which is correct.', status: 'Open' },
  { id: 'rfi-2', projectId: 'proj-1', rfiNumber: 'RFI-002', dateSubmitted: '2024-07-15', subject: 'Specified window manufacturer lead time', question: 'The specified window manufacturer (Model XYZ) has a 16-week lead time, which will impact the schedule. Can we approve an alternate?', status: 'Closed', answer: 'Alternate manufacturer "ABC Windows" is approved. Proceed with substitution.', dateAnswered: '2024-07-18' },
];

export const issues: Issue[] = [
  { id: 'issue-1', projectId: 'proj-1', date: '2024-07-22', severity: 'High', description: 'Unforeseen rock formation discovered during excavation for foundation.', status: 'Open' },
  { id: 'issue-2', projectId: 'proj-3', date: '2023-08-10', severity: 'Low', description: 'Incorrect paint color used in master bathroom. Needs to be repainted.', status: 'Closed', correctiveAction: 'Repainted with correct color (SW-7005) on 2023-08-12.' },
];

export const budgetItems: BudgetItem[] = [
  { id: 'bi-1', projectId: 'proj-1', category: 'Steel', costType: 'material', originalBudget: 15000000, approvedCOBudget: 0, committedCost: 14500000, projectedCost: 14500000 },
  { id: 'bi-2', projectId: 'proj-1', category: 'Concrete', costType: 'material', originalBudget: 10000000, approvedCOBudget: 500000, committedCost: 10200000, projectedCost: 10500000 },
  { id: 'bi-3', projectId: 'proj-1', category: 'Electrical', costType: 'both', originalBudget: 8000000, approvedCOBudget: 0, committedCost: 7500000, projectedCost: 8000000 },
  { id: 'bi-4', projectId: 'proj-2', category: 'Site Work', costType: 'labor', originalBudget: 1200000, approvedCOBudget: 0, committedCost: 1100000, projectedCost: 1200000 },
  { id: 'bi-5', projectId: 'proj-3', category: 'Finishes', costType: 'material', originalBudget: 750000, approvedCOBudget: 50000, committedCost: 800000, projectedCost: 800000 },
];

export const expenses: Expense[] = [
  { id: 'exp-1', projectId: 'proj-1', date: '2024-07-25', category: 'Steel', vendorName: 'Structural Steel Inc.', description: 'Payment for steel delivery #3', amount: 250000, paymentMethod: 'Check', paymentReference: 'CHK-1054' },
  { id: 'exp-2', projectId: 'proj-1', date: '2024-07-26', category: 'Concrete', vendorName: 'City Concrete', description: 'Concrete pour for foundation slab', amount: 120000, paymentMethod: 'ACH' },
  { id: 'exp-3', projectId: 'proj-4', date: '2025-08-12', category: '.GROUNDBREAK', vendorName: 'Shooker Moula', description: 'Groundbroke on', amount: 0, paymentMethod: 'Groundbreaking' },
  { id: 'exp-4', projectId: 'proj-4', date: '2025-08-10', category: 'Pollution Control', vendorName: 'Fabco', description: 'Stand wired back silt fence + t post + ratchet stap + marking paint + twisted twine string', amount: 1182.36, paymentMethod: 'Credit Card', paymentReference: '5663', invoiceNumber: '2404185-118' },
  { id: 'exp-5', projectId: 'proj-4', date: '2025-08-15', category: 'Rental', vendorName: 'Dumpster Dogs TX', description: 'Potty rental initiated, 1st month $179+$50setup $179/mo - 28 days', amount: 229, paymentMethod: 'Credit Card', paymentReference: '5663', invoiceNumber: 'Initial charge' },
  { id: 'exp-6', projectId: 'proj-4', date: '2025-08-18', category: 'Steel', vendorName: 'Triple-S Steel Holdings Inc', description: 'Material for barjoist (material cost $42,688.29 + tax + freight cost $1055.44)', amount: 43743.73, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: 'RS-651836' },
  { id: 'exp-7', projectId: 'proj-4', date: '2025-08-20', category: 'Survey', vendorName: 'Lone Star Mapping', description: 'Construction Staking', amount: 1500, paymentMethod: 'Credit Card', paymentReference: '5663', invoiceNumber: '1374' },
  { id: 'exp-8', projectId: 'proj-4', date: '2025-08-20', category: 'Get Reimbursed', vendorName: 'City Of Temple TX', description: 'Temporary fire hydrant water meter', amount: 600, paymentMethod: 'Credit Card', paymentReference: '5663', invoiceNumber: '13' },
  { id: 'exp-9', projectId: 'proj-4', date: '2025-08-20', category: 'Steel', vendorName: 'Triple-S Steel Holdings Inc', description: 'Material for barjoist (material cost $42,688.29 + (freight cost $1055.44)', amount: 1055.45, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: 'RS-651836' },
  { id: 'exp-10', projectId: 'proj-4', date: '2025-08-22', category: 'Steel', vendorName: 'Carlos Osorto', description: 'Ttl Cntrct $55k labor, prv bal $55k, pd tdy $5k, new bal $50k', amount: 5000, paymentMethod: 'Check', paymentReference: '5433', invoiceNumber: '1st pmt' },
  { id: 'exp-11', projectId: 'proj-4', date: '2025-08-22', category: 'Pollution Control', vendorName: 'Jose Ramirez', description: "White Cap - 140N 15' x 360' Non Woven 600 SY Mirafi", amount: 790.21, paymentMethod: 'Check', paymentReference: '5434', invoiceNumber: '67839274' },
  { id: 'exp-12', projectId: 'proj-4', date: '2025-08-22', category: 'Pollution Control', vendorName: 'Jose Ramirez', description: 'Terrazas Construction - 24 yrd bullrock load', amount: 825, paymentMethod: 'Check', paymentReference: '5434', invoiceNumber: 'Bullrock' },
  { id: 'exp-13', projectId: 'proj-4', date: '2025-08-22', category: 'Dirtwork-Lbr', vendorName: 'Jose Ramirez', description: 'Labor to cut all the trees and clear the land with vegetation (Haul off separate approx 40 loads)', amount: 7500, paymentMethod: 'Check', paymentReference: '5434', invoiceNumber: 'Dirtwork' },
  { id: 'exp-14', projectId: 'proj-4', date: '2025-08-23', category: 'Steel', vendorName: 'Triple-S Steel Holdings Inc', description: 'Material for barjoist (material cost $32,281.85 + tax + freight cost $650)', amount: 32281.85, paymentMethod: 'Credit Card', paymentReference: '5663', invoiceNumber: 'RS-659821' },
  { id: 'exp-15', projectId: 'proj-4', date: '2025-08-23', category: 'Steel', vendorName: 'Triple-S Steel Holdings Inc', description: 'Material for barjoist (material cost $32,281.85 + tax + (freight cost $650)', amount: 650, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: '652659' },
  { id: 'exp-16', projectId: 'proj-4', date: '2025-08-26', category: 'Haul Off', vendorName: 'Jose Ramirez', description: '42 x $160 haul off + $360 extra charge for over load (more to come)', amount: 7080, paymentMethod: 'Check', paymentReference: '5436', invoiceNumber: 'Haul Off' },
  { id: 'exp-17', projectId: 'proj-4', date: '2025-08-26', category: 'Haul Off', vendorName: 'Jose Ramirez', description: '4 x backhoe with operator to haul off heavy tree trunks', amount: 2200, paymentMethod: 'Check', paymentReference: '5436', invoiceNumber: 'Haul Off' },
  { id: 'exp-18', projectId: 'proj-4', date: '2025-08-26', category: 'Sitework-Mtrl', vendorName: 'Jose Ramirez', description: 'Ttl Base back fill needed 370 loads x this time charged $370 ea, x24 1st of 15', amount: 8880, paymentMethod: 'Check', paymentReference: '5436', invoiceNumber: 'Sitework' },
  { id: 'exp-19', projectId: 'proj-4', date: '2025-08-28', category: 'Steel', vendorName: 'Triple-S Steel Holdings Inc', description: 'Material for barjoist (material cost $11,196.42 + tax + freight cost $703.64)', amount: 11196.42, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: 'RS-667851' },
  { id: 'exp-20', projectId: 'proj-4', date: '2025-08-28', category: 'Steel', vendorName: 'Triple-S Steel Holdings Inc', description: 'Material for barjoist (material cost $11,196.42 + tax + freight cost $703.64)', amount: 703.64, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: 'RS-667851' },
  { id: 'exp-21', projectId: 'proj-4', date: '2025-08-30', category: 'Foundation-Main', vendorName: 'Jose Ramirez', description: 'Foundation LABOR ttl $31500, prv bal $31500, pd tdy $10k, bal $21500', amount: 10000, paymentMethod: 'Check', paymentReference: '5437', invoiceNumber: '1st foundation chk' },
  { id: 'exp-22', projectId: 'proj-4', date: '2025-08-31', category: 'Foundation-Main', vendorName: 'Tex-Mix Partners Ltd', description: 'Foundation footings concrete 34 yd 3000 psi x $130 ea + tax', amount: 4938.37, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: 'Concrete fndtion' },
  { id: 'exp-23', projectId: 'proj-4', date: '2025-09-03', category: 'Pollution Control', vendorName: 'SD Construction Material', description: '3/4"x18" Nail stake w/holes for securing silt fences', amount: 267.38, paymentMethod: 'Credit Card', paymentReference: '5663', invoiceNumber: '16225' },
  { id: 'exp-24', projectId: 'proj-4', date: '2025-09-04', category: 'Plumbing', vendorName: 'Leon Plumbing', description: 'TTl cntrct $75K, prv bal $75k, pd tdy $10k, bal $65k', amount: 10000, paymentMethod: 'Check', paymentReference: '5444', invoiceNumber: '1st chk' },
  { id: 'exp-25', projectId: 'proj-4', date: '2025-09-05', category: 'Sitework-Mtrl', vendorName: 'Jose Ramirez', description: 'Ttl Base back fill needed 370 loads x this time charged $360 ea, x42 2nd of 15', amount: 15120, paymentMethod: 'Check', paymentReference: '5446', invoiceNumber: 'Sitework' },
  { id: 'exp-26', projectId: 'proj-4', date: '2025-09-05', category: 'Haul Off', vendorName: 'Jose Ramirez', description: '21 x $160 branches haul off + spoil haul 13 x $150', amount: 5310, paymentMethod: 'Check', paymentReference: '5446', invoiceNumber: 'Haul Off' },
  { id: 'exp-27', projectId: 'proj-4', date: '2025-09-05', category: 'Rental', vendorName: 'Jose Ramirez', description: 'Diesel for all the equipment up to Aug 31 2025', amount: 1400, paymentMethod: 'Check', paymentReference: '5446', invoiceNumber: 'Diesel Fuel' },
  { id: 'exp-28', projectId: 'proj-4', date: '2025-09-13', category: 'Electrical', vendorName: 'A & G Electric', description: 'Elec.Cntrct $245k, prv bal $245k, pd tdy $15k, new bal: $230k', amount: 15000, paymentMethod: 'Check', paymentReference: '2448', invoiceNumber: '1st check' },
  { id: 'exp-29', projectId: 'proj-4', date: '2025-09-15', category: 'Rental', vendorName: 'Dumpster Dogs TX', description: 'Potty rental renewal', amount: 179, paymentMethod: 'Credit Card', paymentReference: '5663', invoiceNumber: '2nd month' },
  { id: 'exp-30', projectId: 'proj-4', date: '2025-09-16', category: 'Steel', vendorName: 'Henry Osorto', description: 'Ttl Cntrct $55k labor, prv bal $50k, pd tdy $15k, new bal $35k', amount: 15000, paymentMethod: 'Check', paymentReference: '5451', invoiceNumber: '2nd pmt' },
  { id: 'exp-31', projectId: 'proj-4', date: '2025-09-18', category: 'Plumbing', vendorName: 'Leon Plumbing', description: 'TTl cntrct $75K, prv bal $65k, pd tdy $15k, bal $50k (underground work completed)', amount: 15000, paymentMethod: 'Check', paymentReference: '5455', invoiceNumber: '2nd chk' },
  { id: 'exp-32', projectId: 'proj-4', date: '2025-09-18', category: 'Foundation-Labor', vendorName: 'Jose Ramirez', description: 'Foundation LABOR ttl $31500, prv bal $21500, PAID OFF', amount: 21500, paymentMethod: 'Check', paymentReference: '5456', invoiceNumber: 'PAID OFF' },
  { id: 'exp-33', projectId: 'proj-4', date: '2025-09-18', category: 'Rental', vendorName: 'United Rental', description: 'Mini excavator for installing silt fences 08/08/25-08/14/25 Check#H20250918', amount: 1989.92, paymentMethod: 'Bank ACH', paymentReference: 'Bank ACH', invoiceNumber: '251514881-001' },
  { id: 'exp-34', projectId: 'proj-4', date: '2025-09-18', category: 'Rental', vendorName: 'United Rental', description: 'Wood Chipper to chip off the smaller trees 8/12/25-8/14/25 Check#H20250918', amount: 1656.31, paymentMethod: 'Bank ACH', paymentReference: 'Bank ACH', invoiceNumber: '251631202-001' },
  { id: 'exp-35', projectId: 'proj-4', date: '2025-09-18', category: 'Rental', vendorName: 'United Rental', description: 'Wood Chipper repair Check#H20250918', amount: 13.56, paymentMethod: 'Bank ACH', paymentReference: 'Bank ACH', invoiceNumber: '251851261-001' },
  { id: 'exp-36', projectId: 'proj-4', date: '2025-09-18', category: 'Rental', vendorName: 'United Rental', description: 'EXCAVATOR BUCKET 36" Check#H20250918', amount: 4568.61, paymentMethod: 'Bank ACH', paymentReference: 'Bank ACH', invoiceNumber: '252117148-001' },
  { id: 'exp-37', projectId: 'proj-4', date: '2025-09-18', category: 'Parking lot', vendorName: 'Jorge De Los Santos', description: '4 stab. sand $680ea,4x bank sand $230ea + haul off dirt and concrete $1892.09 (reimbursed on 10/03/25)', amount: 5532.09, paymentMethod: "Karim's Card", paymentReference: "Karim's Card", invoiceNumber: 'Parking lot' },
  { id: 'exp-38', projectId: 'proj-4', date: '2025-09-18', category: 'Plumbing', vendorName: 'Gatco New Braunfels', description: 'TTl cntrct $75K, prv bal $50k, pd tdy $5102.52, bal $44897.48', amount: 5102.52, paymentMethod: 'Check', paymentReference: '5458', invoiceNumber: '3rd chk' },
  { id: 'exp-39', projectId: 'proj-4', date: '2025-09-18', category: 'Plumbing', vendorName: 'Leon Plumbing', description: 'TTl cntrct $75K, prv bal $44897.48, pd tdy $4897.48, bal $40k', amount: 4897.48, paymentMethod: 'Check', paymentReference: '5459', invoiceNumber: '4th chk' },
  { id: 'exp-40', projectId: 'proj-4', date: '2025-09-25', category: 'Steel', vendorName: 'Triple-S Steel Holdings Inc', description: 'Full order cost, excluding decking and delivery (Grand ttl $163,418.31),', amount: 42817.91, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: 'RS-293988' },
  { id: 'exp-41', projectId: 'proj-4', date: '2025-09-26', category: 'Sitework-Mtrl', vendorName: 'Jose Ramirez', description: 'Ttl Base back fill needed 370 loads x this time charged $360 ea, x63 3rd of 15', amount: 22680, paymentMethod: 'Check', paymentReference: '5461', invoiceNumber: 'Back fill' },
  { id: 'exp-42', projectId: 'proj-4', date: '2025-09-29', category: 'Foundation-Mtrl', vendorName: 'Tex Mix Concrete Mix', description: 'Foundation pour', amount: 53448.44, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: 'Foundtion Pour' },
  { id: 'exp-43', projectId: 'proj-4', date: '2025-10-01', category: 'Parking lot-Mtrl', vendorName: 'Espinoza Stone Inc.', description: '3500 psi x 500 loads concrete $136/ld + $25/ld fee x 50 loads, for partial parking lot', amount: 74963.13, paymentMethod: 'Credit Card', paymentReference: '5663', invoiceNumber: 'ESP11864' },
  { id: 'exp-44', projectId: 'proj-4', date: '2025-10-04', category: 'Steel', vendorName: 'Triple-S Steel Holdings Inc', description: 'Full order cost, excluding decking and delivery (Grand ttl $163,418.31),', amount: 13667.56, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: 'RS-295180' },
  { id: 'exp-45', projectId: 'proj-4', date: '2025-10-04', category: 'Get Reimbursed', vendorName: 'City Of Temple TX', description: 'Temporary fire hydrant water meter usage fee acct# 41333-0', amount: 177.59, paymentMethod: 'Credit Card', paymentReference: '5663', invoiceNumber: '4015841' },
  { id: 'exp-46', projectId: 'proj-4', date: '2025-10-06', category: 'Rental', vendorName: 'Sunrise Creek Pumping, LLC', description: 'Partial parking lot pour, approix. 500 yards', amount: 5547.6, paymentMethod: 'Bank ACH', paymentReference: 'Bank ACH', invoiceNumber: '456631' },
  { id: 'exp-47', projectId: 'proj-4', date: '2025-10-07', category: 'Steel', vendorName: 'Triple-S Steel Holdings Inc', description: 'Full order cost, excluding decking and delivery (Grand ttl $163,418.31),', amount: 12530.94, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: 'RS-295180' },
  { id: 'exp-48', projectId: 'proj-4', date: '2025-10-07', category: 'Rental', vendorName: 'Sunrise Creek Pumping, LLC', description: 'Foundation pour, approx. 250 yards', amount: 3266, paymentMethod: 'Bank ACH', paymentReference: 'Bank ACH', invoiceNumber: '456353' },
  { id: 'exp-49', projectId: 'proj-4', date: '2025-10-07', category: 'Parking lot', vendorName: 'The Kings Transport', description: 'Hauled off excess dirt and concrete wash concrete (to be reimburesed)', amount: 4896.76, paymentMethod: "Karim's Card", paymentReference: "Karim's Card", invoiceNumber: 'Parking lot' },
  { id: 'exp-50', projectId: 'proj-4', date: '2025-10-09', category: 'Steel', vendorName: 'Carlos Osorto', description: 'Ttl Cntrct $55k labor, prv bal $35k, pd tdy $15k, new bal $20k', amount: 15000, paymentMethod: 'Check', paymentReference: '5468', invoiceNumber: '3rd pmt' },
  { id: 'exp-51', projectId: 'proj-4', date: '2025-10-09', category: 'Foundation-Mtrl', vendorName: 'GC Rebar', description: 'Ttl inv# 14441 $27669.86, FOUNDATION mtrl $22365.86', amount: 22365.86, paymentMethod: 'Check', paymentReference: '5469', invoiceNumber: '14441' },
  { id: 'exp-52', projectId: 'proj-4', date: '2025-10-09', category: 'Parking lot', vendorName: 'GC Rebar', description: 'Ttl inv# 14441 $27669.86, parking lot $5304, got it because of big truck freight', amount: 5304, paymentMethod: 'Check', paymentReference: '5469', invoiceNumber: '14441' },
  { id: 'exp-53', projectId: 'proj-4', date: '2025-10-09', category: 'Foundation-Mtrl', vendorName: 'GC Rebar', description: 'CUSTOM FAB 12"X24"X12" #3 (3/8") U BAR, 8"X45"X8" #5 (5/8") STRAIGHT BODY Z BAR', amount: 550.13, paymentMethod: 'Check', paymentReference: '5469', invoiceNumber: '14465' },
  { id: 'exp-54', projectId: 'proj-4', date: '2025-10-09', category: 'Parking lot-Labor', vendorName: 'Jose Ramirez', description: 'Parkinglot ttl sf 40k sf $65k, poured 26k sf, remaining 14k sf, prv bal, $65k, pd tdy $39k, bal $26k', amount: 39000, paymentMethod: 'Check', paymentReference: '5470', invoiceNumber: '1st prkng lt Lbr' },
  { id: 'exp-55', projectId: 'proj-4', date: '2025-10-09', category: 'Rental', vendorName: 'Jose Ramirez', description: 'Skidsteer one month', amount: 3400, paymentMethod: 'Check', paymentReference: '5470', invoiceNumber: 'Rental' },
  { id: 'exp-56', projectId: 'proj-4', date: '2025-10-09', category: 'Rental', vendorName: 'Dumpster Dogs TX', description: 'Potty rental renewal', amount: 179, paymentMethod: 'Credit Card', paymentReference: '5663', invoiceNumber: '3rd month' },
  { id: 'exp-57', projectId: 'proj-4', date: '2025-10-09', category: 'Rental', vendorName: 'The Kings Transport', description: '2 x 40 yards dumpter swaps $943.44 ea (to be reimburese)', amount: 1886.88, paymentMethod: "Karim's Card", paymentReference: "Karim's Card", invoiceNumber: 'Rental' },
  { id: 'exp-58', projectId: 'proj-4', date: '2025-10-14', category: 'Rental', vendorName: 'Texas State Rentals', description: 'Forklift,Telescopic, 9000-10,000lb 2 to 3 months (08/20/25-09/17/25) 1st month', amount: 5740.29, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: '37625-6' },
  { id: 'exp-59', projectId: 'proj-4', date: '2025-10-14', category: 'Rental', vendorName: 'Texas State Rentals', description: '12" Bucket for SY26+24" Bucket for SY35+Sany SY26 Mini Excavator (08/22/25-09/19/25)', amount: 2749.62, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: '37684-6' },
  { id: 'exp-60', projectId: 'proj-4', date: '2025-10-14', category: 'Rental', vendorName: 'Texas State Rentals', description: 'Ammann ARS70 Roller, 66" ACZ15184PN3031392 (08/22/25-09/19/25)', amount: 4565.49, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: '37687-6' },
  { id: 'exp-61', projectId: 'proj-4', date: '2025-10-14', category: 'Rental', vendorName: 'Texas State Rentals', description: 'Dozer, CASE 650 or Cat D4 -rented (09/09/2025-10/07/25) FINAL', amount: 4307.6, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: '37514A-6' },
  { id: 'exp-62', projectId: 'proj-4', date: '2025-10-14', category: 'Rental', vendorName: 'Texas State Rentals', description: 'Dozer, CASE 650 or Cat D4 -rented (08/12/2025-09/08/25)', amount: 6088.91, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: '37514-6' },
  { id: 'exp-63', projectId: 'proj-4', date: '2025-10-14', category: 'Rental', vendorName: 'Texas State Rentals', description: 'Forklift,Telescopic, 9000-10,000lb 2 to 3 months (09/17/25-10-15-25) 2nd month', amount: 5090.79, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: '37636A-6' },
  { id: 'exp-64', projectId: 'proj-4', date: '2025-10-14', category: 'Rental', vendorName: 'Texas State Rentals', description: '12" Bucket for SY26+24" Bucket for SY35+Sany SY26 Mini Excavator (09/19/25-10/03/25) FINAL', amount: 2134.89, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: '37684A-6' },
  { id: 'exp-65', projectId: 'proj-4', date: '2025-10-14', category: 'Rental', vendorName: 'Texas State Rentals', description: 'Ammann ARS70 Roller, 66" ACZ15184PN3031392 (09/19/25-10/01/25) FINAL', amount: 1566.4, paymentMethod: 'Credit Card', paymentReference: '1769', invoiceNumber: '3768A-6' },
  { id: 'exp-66', projectId: 'proj-4', date: '2025-10-14', category: 'Rental', vendorName: 'Texas State Rentals', description: 'Forklift,Telescopic, 9000-10,000lb 3 to 3 months (10-15-25-11-12-25) 3rd month', amount: 5090.79, paymentMethod: 'to be paid', paymentReference: 'to be paid', invoiceNumber: '376836B-6' },
  { id: 'exp-67', projectId: 'proj-4', date: '2025-10-15', category: 'Parking lot-Mtrl', vendorName: 'GC Rebar', description: '#4 rebar and other parkinglot material', amount: 30472.36, paymentMethod: 'to be paid', paymentReference: 'to be paid', invoiceNumber: '14822' },
  { id: 'exp-68', projectId: 'proj-4', date: '2025-10-16', category: 'Parking lot-Mtrl', vendorName: 'GC Rebar', description: 'Parkinglot material', amount: 4495.97, paymentMethod: 'to be paid', paymentReference: 'to be paid', invoiceNumber: '15029' },
  { id: 'exp-69', projectId: 'proj-4', date: '2025-10-17', category: 'Parking lot-Mtrl', vendorName: 'GC Rebar', description: 'Parkinglot material', amount: 1740.12, paymentMethod: 'to be paid', paymentReference: 'to be paid', invoiceNumber: '15325' },
  { id: 'exp-70', projectId: 'proj-4', date: '2025-10-18', category: 'Steel', vendorName: 'Triple-S Steel Holdings Inc', description: 'Full order cost, excluding decking and delivery (Grand ttl $163,418.31), remaining amount', amount: 32043.88, paymentMethod: 'to be paid', paymentReference: 'to be paid', invoiceNumber: 'RS-651204' },
];

export const changeOrders: ChangeOrder[] = [
    { id: 'co-1', projectId: 'proj-1', coNumber: 'CO-001', description: 'Increase electrical capacity for 10th floor data center.', totalRequest: 125000, status: 'Approved' },
    { id: 'co-2', projectId: 'proj-1', coNumber: 'CO-002', description: 'Owner requested change to lobby finishes.', totalRequest: 75000, status: 'Submitted' },
    { id: 'co-3', projectId: 'proj-3', coNumber: 'CO-001', description: 'Add outdoor kitchen to patio.', totalRequest: 50000, status: 'Executed' },
];
