
import type { Project, TeamMember, Vendor, BudgetCategory, Task, RFI, Issue, BudgetItem, Expense, ChangeOrder } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const teamMembers: TeamMember[] = [];

export const vendors: Vendor[] = [];

export const budgetCategories: BudgetCategory[] = [];

export const projects: Project[] = [];

export const tasks: Task[] = [];

export const rfis: RFI[] = [];

export const issues: Issue[] = [];

export const budgetItems: BudgetItem[] = [];

export const expenses: Expense[] = [
  {
    "id": "1",
    "projectId": "1",
    "date": "2025-08-12",
    "category": "GROUNDBREAK",
    "vendorName": "Shooker Moula",
    "description": "Groundbroke on",
    "amount": 1182.36,
    "paymentMethod": "Credit Card",
    "paymentReference": "5663",
    "invoiceNumber": "2404185-118"
  },
  {
    "id": "2",
    "projectId": "1",
    "date": "2025-08-10",
    "category": "Pollution Control",
    "vendorName": "Fabco",
    "description": "Stand wired back silt fence + t post + ratchet stap + marking paint + twisted twine string",
    "amount": 229,
    "paymentMethod": "Credit Card",
    "paymentReference": "5663",
    "invoiceNumber": "Initial charge"
  },
  {
    "id": "3",
    "projectId": "1",
    "date": "2025-08-15",
    "category": "Rental",
    "vendorName": "Dumpster Dogs TX",
    "description": "Potty rental initiated, 1st month $179+$50setup $179/mo-28 days",
    "amount": 43743.73,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "RS-651836"
  },
  {
    "id": "4",
    "projectId": "1",
    "date": "2025-08-18",
    "category": "Steel",
    "vendorName": "Triple-S Steel Holdings Inc",
    "description": "Material for barjoist (material cost $42,688.29 + tax + freight cost $1055.44)",
    "amount": 1500,
    "paymentMethod": "Credit Card",
    "paymentReference": "5663",
    "invoiceNumber": "1374"
  },
  {
    "id": "5",
    "projectId": "1",
    "date": "2025-08-20",
    "category": "Survey",
    "vendorName": "Lone Star Mapping",
    "description": "Construction Staking",
    "amount": 600,
    "paymentMethod": "Credit Card",
    "paymentReference": "5663",
    "invoiceNumber": "13"
  },
  {
    "id": "6",
    "projectId": "1",
    "date": "2025-08-20",
    "category": "Get Reimbursed",
    "vendorName": "City Of Temple TX",
    "description": "Temporary fire hydrant water meter",
    "amount": 1055.45,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "RS-651836"
  },
  {
    "id": "7",
    "projectId": "1",
    "date": "2025-08-20",
    "category": "Steel",
    "vendorName": "Triple-S Steel Holdings Inc",
    "description": "Material for barjoist (material cost $42,688.29 + (freight cost $1055.44)",
    "amount": 5000,
    "paymentMethod": "Check",
    "paymentReference": "5433",
    "invoiceNumber": "1st pmt"
  },
  {
    "id": "8",
    "projectId": "1",
    "date": "2025-08-22",
    "category": "Steel",
    "vendorName": "Carlos Osorto",
    "description": "Ttl Cntrot $55k labor, prv bal $55k, pd tdy $5k, new bal $50k",
    "amount": 790.21,
    "paymentMethod": "Check",
    "paymentReference": "5434",
    "invoiceNumber": "167839274"
  },
  {
    "id": "9",
    "projectId": "1",
    "date": "2025-08-22",
    "category": "Pollution Control",
    "vendorName": "Jose Ramirez",
    "description": "White Cap-140N 15' x 360' Non Woven 600 SY Mirafi",
    "amount": 825,
    "paymentMethod": "Check",
    "paymentReference": "5434",
    "invoiceNumber": "Bullrock"
  },
  {
    "id": "10",
    "projectId": "1",
    "date": "2025-08-22",
    "category": "Pollution Control",
    "vendorName": "Jose Ramirez",
    "description": "Terrazas Construction-24 yrd bullrock load",
    "amount": 7500,
    "paymentMethod": "Check",
    "paymentReference": "5434",
    "invoiceNumber": "Dirtwork"
  },
  {
    "id": "11",
    "projectId": "1",
    "date": "2025-08-22",
    "category": "Dirtwork-Lbr",
    "vendorName": "Jose Ramirez",
    "description": "Labor to cut all the trees and clear the land with vegetation (Haul off separate approx 40 loads)",
    "amount": 32281.85,
    "paymentMethod": "Credit Card",
    "paymentReference": "5663",
    "invoiceNumber": "RS-659821"
  },
  {
    "id": "12",
    "projectId": "1",
    "date": "2025-08-23",
    "category": "Steel",
    "vendorName": "Triple-S Steel Holdings Inc",
    "description": "Material for barjoist (material cost $32,281.85 + tax + freight cost $650)",
    "amount": 650,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "652659"
  },
  {
    "id": "13",
    "projectId": "1",
    "date": "2025-08-23",
    "category": "Steel",
    "vendorName": "Triple-S Steel Holdings Inc",
    "description": "Material for barjoist (material cost $32,281.85 + tax + (freight cost $650)",
    "amount": 7080,
    "paymentMethod": "Check",
    "paymentReference": "5436",
    "invoiceNumber": "Haul Off"
  },
  {
    "id": "14",
    "projectId": "1",
    "date": "2025-08-26",
    "category": "Haul Off",
    "vendorName": "Jose Ramirez",
    "description": "42 x $160 haul off + $360 extra charge for over load (more to come)",
    "amount": 2200,
    "paymentMethod": "Check",
    "paymentReference": "5436",
    "invoiceNumber": "Haul Off"
  },
  {
    "id": "15",
    "projectId": "1",
    "date": "2025-08-26",
    "category": "Haul Off",
    "vendorName": "Jose Ramirez",
    "description": "4 x backhoe with operator to haul off heavy tree trunks",
    "amount": 8880,
    "paymentMethod": "Check",
    "paymentReference": "5436",
    "invoiceNumber": "Sitework"
  },
  {
    "id": "16",
    "projectId": "1",
    "date": "2025-08-26",
    "category": "Sitework-Mtrl",
    "vendorName": "Jose Ramirez",
    "description": "Ttl Base back fill needed 370 loads x $370 ea, x24 1st of 15",
    "amount": 11196.42,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "RS-667851"
  },
  {
    "id": "17",
    "projectId": "1",
    "date": "2025-08-28",
    "category": "Steel",
    "vendorName": "Triple-S Steel Holdings Inc",
    "description": "Material for barjoist (material cost $11,196.42 + tax + freight cost $703.64)",
    "amount": 703.64,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "RS-667851"
  },
  {
    "id": "18",
    "projectId": "1",
    "date": "2025-08-28",
    "category": "Steel",
    "vendorName": "Triple-S Steel Holdings Inc",
    "description": "Material for barjoist (material cost $11,196.42 + tax + freight cost $703.64)",
    "amount": 10000,
    "paymentMethod": "Check",
    "paymentReference": "5437",
    "invoiceNumber": "1st foundation chk"
  },
  {
    "id": "19",
    "projectId": "1",
    "date": "2025-08-30",
    "category": "Foundation-Main",
    "vendorName": "Tex-Mix Partners Ltd",
    "description": "Foundation LABOR ttl $31500, pry bal $31500, pd tdy $10k, bal $21500",
    "amount": 4938.37,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "Concrete fndtion"
  },
  {
    "id": "20",
    "projectId": "1",
    "date": "2025-08-31",
    "category": "Foundation-Main",
    "vendorName": "SD Construction Material",
    "description": "Foundation footings concrete 34 yd 3000 psi x $130 ea + tax",
    "amount": 267.38,
    "paymentMethod": "Credit Card",
    "paymentReference": "5663",
    "invoiceNumber": "16225"
  },
  {
    "id": "21",
    "projectId": "1",
    "date": "2025-09-03",
    "category": "Pollution Control",
    "vendorName": "Jose Ramirez",
    "description": "3/4\"x18\" Nail stake w/holes for securing silt fences",
    "amount": 10000,
    "paymentMethod": "Check",
    "paymentReference": "5444",
    "invoiceNumber": "1st chk"
  },
  {
    "id": "22",
    "projectId": "1",
    "date": "2025-09-04",
    "category": "Plumbing",
    "vendorName": "Leon Plumbing",
    "description": "TTI entrat $75K, prv bal $75k, pd tdy $10k, bal $65k",
    "amount": 15120,
    "paymentMethod": "Check",
    "paymentReference": "5446",
    "invoiceNumber": "Sitework"
  },
  {
    "id": "23",
    "projectId": "1",
    "date": "2025-09-05",
    "category": "Sitework-Mtrl",
    "vendorName": "Jose Ramirez",
    "description": "Ttl Base back fill needed 370 loads x this time charged $360 ea, x42 2nd of 15",
    "amount": 5310,
    "paymentMethod": "Check",
    "paymentReference": "5446",
    "invoiceNumber": "Haul Off"
  },
  {
    "id": "24",
    "projectId": "1",
    "date": "2025-09-05",
    "category": "Haul Off",
    "vendorName": "Jose Ramirez",
    "description": "21x $160 branches haul off + spoil haul 13 x $150",
    "amount": 1400,
    "paymentMethod": "Check",
    "paymentReference": "5446",
    "invoiceNumber": "Diesel Fuel"
  },
  {
    "id": "25",
    "projectId": "1",
    "date": "2025-09-05",
    "category": "Rental",
    "vendorName": "Jose Ramirez",
    "description": "Diesel for all the equipment up to Aug 312025",
    "amount": 15000,
    "paymentMethod": "Check",
    "paymentReference": "2448",
    "invoiceNumber": "1st check"
  },
  {
    "id": "26",
    "projectId": "1",
    "date": "2025-09-13",
    "category": "Electrical",
    "vendorName": "A & G Electrio",
    "description": "Elec.Cntrot $245k, prv bal $245k, pd tdy $15k, new bal: $230k",
    "amount": 179,
    "paymentMethod": "Credit Card",
    "paymentReference": "5663",
    "invoiceNumber": "2nd month"
  },
  {
    "id": "27",
    "projectId": "1",
    "date": "2025-09-15",
    "category": "Rental",
    "vendorName": "Dumpster Dogs TX",
    "description": "Potty rental renewal",
    "amount": 15000,
    "paymentMethod": "Check",
    "paymentReference": "5451",
    "invoiceNumber": "2nd pmt"
  },
  {
    "id": "28",
    "projectId": "1",
    "date": "2025-09-16",
    "category": "Steel",
    "vendorName": "Henry Osorto",
    "description": "Ttl Cntrot $55k labor, prv bal $50k, pd tdy $15k, new bal $35k",
    "amount": 15000,
    "paymentMethod": "Check",
    "paymentReference": "5455",
    "invoiceNumber": "2nd chk"
  },
  {
    "id": "29",
    "projectId": "1",
    "date": "2025-09-18",
    "category": "Plumbing",
    "vendorName": "Leon Plumbing",
    "description": "TTI entrat $75K, prv bal $65k, pd tdy $15k, bal $50k (underground work completed)",
    "amount": 21500,
    "paymentMethod": "Check",
    "paymentReference": "5456",
    "invoiceNumber": "PAID OFF"
  },
  {
    "id": "30",
    "projectId": "1",
    "date": "2025-09-18",
    "category": "Foundation-Labor",
    "vendorName": "Jose Ramirez",
    "description": "Foundation LABOR ttl $31500, prv bal $21500, PAID OFF",
    "amount": 1989.92,
    "paymentMethod": "Bank ACH",
    "paymentReference": "Bank ACH",
    "invoiceNumber": "251514881-001"
  },
  {
    "id": "31",
    "projectId": "1",
    "date": "2025-09-18",
    "category": "Rental",
    "vendorName": "United Rental",
    "description": "Mini excavator for installing silt fences 08/08/25-08/14/25 Check#H20250918",
    "amount": 1656.31,
    "paymentMethod": "Bank ACH",
    "paymentReference": "Bank ACH",
    "invoiceNumber": "251631202-001"
  },
  {
    "id": "32",
    "projectId": "1",
    "date": "2025-09-18",
    "category": "Rental",
    "vendorName": "United Rental",
    "description": "Wood Chipper to chip off the smaller trees 8/12/25-8/14/25 Check#H20250918",
    "amount": 13.56,
    "paymentMethod": "Bank ACH",
    "paymentReference": "Bank ACH",
    "invoiceNumber": "251851261-001"
  },
  {
    "id": "33",
    "projectId": "1",
    "date": "2025-09-18",
    "category": "Rental",
    "vendorName": "United Rental",
    "description": "Wood Chipper repair Check#H20250918",
    "amount": 4568.61,
    "paymentMethod": "Bank ACH",
    "paymentReference": "Bank ACH",
    "invoiceNumber": "252117148-001"
  },
  {
    "id": "34",
    "projectId": "1",
    "date": "2025-09-18",
    "category": "Rental",
    "vendorName": "United Rental",
    "description": "EXCAVATOR BUCKET 36\" Check#H20250918",
    "amount": 5532.09,
    "paymentMethod": "Karim's Card",
    "paymentReference": "Karim's Card",
    "invoiceNumber": "Parking lot"
  },
  {
    "id": "35",
    "projectId": "1",
    "date": "2025-09-18",
    "category": "Parking lot",
    "vendorName": "Jorge De Los Santos",
    "description": "4 stab. sand $680ea, 4x bank sand $230ea + haul off dirt and concrete $1892.09 (reimbursed on 10",
    "amount": 5102.52,
    "paymentMethod": "Check",
    "paymentReference": "5458",
    "invoiceNumber": "3rd chk"
  },
  {
    "id": "36",
    "projectId": "1",
    "date": "2025-09-18",
    "category": "Plumbing",
    "vendorName": "Gatco New Braunfels",
    "description": "TTI entret $75K, prv bal $50k, pd tdy $5102.52, bal $44897.48",
    "amount": 4897.48,
    "paymentMethod": "Check",
    "paymentReference": "5459",
    "invoiceNumber": "4th chk"
  },
  {
    "id": "37",
    "projectId": "1",
    "date": "2025-09-18",
    "category": "Plumbing",
    "vendorName": "Leon Plumbing",
    "description": "TTI entrat $75K, pry bal $44897.48, pd tdy $4897.48, bal $40k",
    "amount": 42817.91,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "RS-293988"
  },
  {
    "id": "38",
    "projectId": "1",
    "date": "2025-09-25",
    "category": "Steel",
    "vendorName": "Triple-S Steel Holdings Inc",
    "description": "Full order cost, excluding decking and delivery (Grand ttl $163,418.31),",
    "amount": 22680,
    "paymentMethod": "Check",
    "paymentReference": "5461",
    "invoiceNumber": "Back fill"
  },
  {
    "id": "39",
    "projectId": "1",
    "date": "2025-09-26",
    "category": "Sitework-Mtrl",
    "vendorName": "Jose Ramirez",
    "description": "Ttl Base back fill needed 370 loads x this time charged $360 ea, x63 3rd of 15",
    "amount": 53448.44,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "Foundtion Pour"
  },
  {
    "id": "40",
    "projectId": "1",
    "date": "2025-09-29",
    "category": "Foundation-Mtrl",
    "vendorName": "Tex Mix Concrete Mix",
    "description": "Foundation pour",
    "amount": 74963.13,
    "paymentMethod": "Credit Card",
    "paymentReference": "5663",
    "invoiceNumber": "ESP11864"
  },
  {
    "id": "41",
    "projectId": "1",
    "date": "2025-10-01",
    "category": "Parking lot-Mtrl",
    "vendorName": "Espinoza Stone Inc.",
    "description": "3500 psi x 500 loads concrete $136/ld + $25/ld fee x 50 loads, for partial parking lot",
    "amount": 13667.56,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "RS-295180"
  },
  {
    "id": "42",
    "projectId": "1",
    "date": "2025-10-04",
    "category": "Steel",
    "vendorName": "Triple-S Steel Holdings Inc",
    "description": "Full order cost, excluding decking and delivery (Grand ttl $163,418.31),",
    "amount": 177.59,
    "paymentMethod": "Credit Card",
    "paymentReference": "5663",
    "invoiceNumber": "4015841"
  },
  {
    "id": "43",
    "projectId": "1",
    "date": "2025-10-04",
    "category": "Get Reimbursed",
    "vendorName": "City Of Temple TX",
    "description": "Temporary fire hydrant water meter usage fee acct# 41333-0",
    "amount": 5547.6,
    "paymentMethod": "Bank ACH",
    "paymentReference": "Bank ACH",
    "invoiceNumber": "456631"
  },
  {
    "id": "44",
    "projectId": "1",
    "date": "2025-10-06",
    "category": "Rental",
    "vendorName": "Sunrise Creek Pumping, LLC",
    "description": "Partial parking lot pour, approix. 500 yards",
    "amount": 12530.94,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "RS-295180"
  },
  {
    "id": "45",
    "projectId": "1",
    "date": "2025-10-07",
    "category": "Steel",
    "vendorName": "Triple-S Steel Holdings Inc",
    "description": "Full order cost, excluding decking and delivery (Grand ttl $163,418.31),",
    "amount": 3266,
    "paymentMethod": "Bank ACH",
    "paymentReference": "Bank ACH",
    "invoiceNumber": "456353"
  },
  {
    "id": "46",
    "projectId": "1",
    "date": "2025-10-07",
    "category": "Rental",
    "vendorName": "Sunrise Creek Pumping, LLC",
    "description": "Foundation pour, approx. 250 yards",
    "amount": 4896.76,
    "paymentMethod": "Karim's Card",
    "paymentReference": "Karim's Card",
    "invoiceNumber": "Parking lot"
  },
  {
    "id": "47",
    "projectId": "1",
    "date": "2025-10-07",
    "category": "Parking lot",
    "vendorName": "The Kings Transport",
    "description": "Hauled off excess dirt and concrete wash concrete (to be reimburesed)",
    "amount": 15000,
    "paymentMethod": "Check",
    "paymentReference": "5468",
    "invoiceNumber": "3rd pmt"
  },
  {
    "id": "48",
    "projectId": "1",
    "date": "2025-10-09",
    "category": "Steel",
    "vendorName": "Carlos Osorto",
    "description": "Ttl Cntrot $55k labor, prv bal $35k, pd tdy $15k, new bal $20k",
    "amount": 22365.86,
    "paymentMethod": "Check",
    "paymentReference": "5469",
    "invoiceNumber": "14441"
  },
  {
    "id": "49",
    "projectId": "1",
    "date": "2025-10-09",
    "category": "Foundation-Mtrl",
    "vendorName": "GC Rebar",
    "description": "Ttlinu# 14441$27669.86, FOUNDATION mtrl $22365.86",
    "amount": 5304,
    "paymentMethod": "Check",
    "paymentReference": "5469",
    "invoiceNumber": "14441"
  },
  {
    "id": "50",
    "projectId": "1",
    "date": "2025-10-09",
    "category": "Parking lot",
    "vendorName": "GC Rebar",
    "description": "Ttlinu# 14441$27669.86, parking lot $5304, got it because of big truck freight",
    "amount": 550.13,
    "paymentMethod": "Check",
    "paymentReference": "5469",
    "invoiceNumber": "14465"
  },
  {
    "id": "51",
    "projectId": "1",
    "date": "2025-10-09",
    "category": "Foundation-Mtrl",
    "vendorName": "GC Rebar",
    "description": "CUSTOM FAB 12\"X24\"X12\" #3 (3/8\") U BAR, 8\"X45\"X8\" #5 (5/8\") STRAIGHT BODY Z BAR",
    "amount": 39000,
    "paymentMethod": "Check",
    "paymentReference": "5470",
    "invoiceNumber": "1st prkng It Lbr"
  },
  {
    "id": "52",
    "projectId": "1",
    "date": "2025-10-09",
    "category": "Parking lot-Labor",
    "vendorName": "Jose Ramirez",
    "description": "Parkinglot ttl sf 40k sf $65k, poured 26k sf, remaining 14k sf, prv bal, $65k, pd tdy $39k, bal $26k",
    "amount": 3400,
    "paymentMethod": "Check",
    "paymentReference": "5470",
    "invoiceNumber": "Rental"
  },
  {
    "id": "53",
    "projectId": "1",
    "date": "2025-10-09",
    "category": "Rental",
    "vendorName": "Jose Ramirez",
    "description": "Skidsteer one month",
    "amount": 179,
    "paymentMethod": "Credit Card",
    "paymentReference": "5663",
    "invoiceNumber": "3rd month"
  },
  {
    "id": "54",
    "projectId": "1",
    "date": "2025-10-09",
    "category": "Rental",
    "vendorName": "Dumpster Dogs TX",
    "description": "Potty rental renewal",
    "amount": 1886.88,
    "paymentMethod": "Karim's Card",
    "paymentReference": "Karim's Card",
    "invoiceNumber": "Rental"
  },
  {
    "id": "55",
    "projectId": "1",
    "date": "2025-10-09",
    "category": "Rental",
    "vendorName": "The Kings Transport",
    "description": "2 x 40 yards dumpter swaps $943.44 ea (to be reimburese)",
    "amount": 5740.29,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "37625-6"
  },
  {
    "id": "56",
    "projectId": "1",
    "date": "2025-10-14",
    "category": "Rental",
    "vendorName": "Texas State Rentals",
    "description": "Forklift, Telescopic, 9000-10,000lb 2 to 3 months (08/20/25-09/17/25) 1st month",
    "amount": 2749.62,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "37684-6"
  },
  {
    "id": "57",
    "projectId": "1",
    "date": "2025-10-14",
    "category": "Rental",
    "vendorName": "Texas State Rentals",
    "description": "12\" Bucket for SY26+24\" Bucket for SY35+Sany SY26 Mini Excavator (08/22/25-09/19/25)",
    "amount": 4565.49,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "37687-6"
  },
  {
    "id": "58",
    "projectId": "1",
    "date": "2025-10-14",
    "category": "Rental",
    "vendorName": "Texas State Rentals",
    "description": "Ammann ARS70 Roller, 66\" ACZ15184PN3031392 (08/22/25-09/19/25)",
    "amount": 4307.6,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "37514A-6"
  },
  {
    "id": "59",
    "projectId": "1",
    "date": "2025-10-14",
    "category": "Rental",
    "vendorName": "Texas State Rentals",
    "description": "Dozer, CASE 650 or Cat D4-rented (09/09/2025-10/07/25) FINAL",
    "amount": 6088.91,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "37514-6"
  },
  {
    "id": "60",
    "projectId": "1",
    "date": "2025-10-14",
    "category": "Rental",
    "vendorName": "Texas State Rentals",
    "description": "Dozer, CASE 650 or Cat D4-rented (08/12/2025-09/08/25)",
    "amount": 5090.79,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "37636A-6"
  },
  {
    "id": "61",
    "projectId": "1",
    "date": "2025-10-14",
    "category": "Rental",
    "vendorName": "Texas State Rentals",
    "description": "Forklift, Telescopic, 9000-10,000lb 2 to 3 months (09/17/25-10-15-25) 2nd month",
    "amount": 2134.89,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "37684A-6"
  },
  {
    "id": "62",
    "projectId": "1",
    "date": "2025-10-14",
    "category": "Rental",
    "vendorName": "Texas State Rentals",
    "description": "12\" Bucket for SY26+24\" Bucket for SY35+Sany SY26 Mini Excavator (09/19/25-10/03/25) FINAL",
    "amount": 1566.4,
    "paymentMethod": "Credit Card",
    "paymentReference": "1769",
    "invoiceNumber": "3768A-6"
  },
  {
    "id": "63",
    "projectId": "1",
    "date": "2025-10-14",
    "category": "Rental",
    "vendorName": "Texas State Rentals",
    "description": "Ammann ARS70 Roller, 66\" ACZ15184PN3031392 (09/19/25-10/01/25) FINAL",
    "amount": 5090.79,
    "paymentMethod": "to be paid",
    "paymentReference": "to be paid",
    "invoiceNumber": "376836B-6"
  },
  {
    "id": "64",
    "projectId": "1",
    "date": "2025-10-14",
    "category": "Rental",
    "vendorName": "Texas State Rentals",
    "description": "Forklift, Telescopic, 9000-10,000lb 3 to 3 months (10-15-25-11-12-25) 3rd month",
    "amount": 30472.36,
    "paymentMethod": "to be paid",
    "paymentReference": "to be paid",
    "invoiceNumber": "14822"
  },
  {
    "id": "65",
    "projectId": "1",
    "date": "2025-10-15",
    "category": "Parking lot-Mtrl",
    "vendorName": "GC Rebar",
    "description": "#4 rebar and other parkinglot material",
    "amount": 4495.97,
    "paymentMethod": "to be paid",
    "paymentReference": "to be paid",
    "invoiceNumber": "15029"
  },
  {
    "id": "66",
    "projectId": "1",
    "date": "2025-10-16",
    "category": "Parking lot-Mtrl",
    "vendorName": "GC Rebar",
    "description": "Parkinglot material",
    "amount": 1740.12,
    "paymentMethod": "to be paid",
    "paymentReference": "to be paid",
    "invoiceNumber": "15325"
  },
  {
    "id": "67",
    "projectId": "1",
    "date": "2025-10-17",
    "category": "Parking lot-Mtrl",
    "vendorName": "GC Rebar",
    "description": "Parkinglot material",
    "amount": 32043.88,
    "paymentMethod": "to be paid",
    "paymentReference": "to be paid",
    "invoiceNumber": "RS-651204"
  },
  {
    "id": "68",
    "projectId": "1",
    "date": "2025-10-18",
    "category": "Steel",
    "vendorName": "Triple-S Steel Holdings Inc",
    "description": "Full order cost, excluding decking and delivery (Grand ttl $163,418.31), remaining amount",
    "amount": 0,
    "paymentMethod": "",
    "paymentReference": "",
    "invoiceNumber": ""
  }
];

export const changeOrders: ChangeOrder[] = [];
