
import type { Project, TeamMember, Vendor, BudgetCategory, Task, RFI, Issue, BudgetItem, Expense, ChangeOrder } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const teamMembers: TeamMember[] = [
    { id: '1', name: 'John Doe', role: 'Project Manager', email: 'john.d@company.com', phone: '123-456-7890', avatarUrl: 'https://i.pravatar.cc/150?u=john' },
    { id: '2', name: 'Jane Smith', role: 'Site Superintendent', email: 'jane.s@company.com', phone: '123-456-7891', avatarUrl: 'https://i.pravatar.cc/150?u=jane' },
    { id: '3', name: 'Mike Johnson', role: 'Estimator', email: 'mike.j@company.com', phone: '123-456-7892', avatarUrl: 'https://i.pravatar.cc/150?u=mike' },
];

export const vendors: Vendor[] = [
    { "id": "1", "name": "A & G Electric", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "2", "name": "A Morfin Trucking LLC", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "3", "name": "ACT PIPE AND SUPPLY, INC.", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "4", "name": "Action Gypsum", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "5", "name": "Advanced LED Solution", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "6", "name": "Alexanders Construction", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "7", "name": "Alif Security LLC", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "8", "name": "Allied Hydromulch TX, LLC", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "9", "name": "Amazon", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "10", "name": "Andrade Construction (Sandra Cruz)", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "11", "name": "Arise Furniture LLC", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "12", "name": "Backflow Technicians", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "13", "name": "Barreras Glass", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "14", "name": "Brent Lowrey", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "15", "name": "Camarillo Trucks", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "16", "name": "Cano", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "17", "name": "Carlos Osorto", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "18", "name": "CNA SURETY", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "19", "name": "Compania Vision", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "20", "name": "Concrete Cleaning Inc. (Polished Concrete)", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "21", "name": "Crow Castle LLC", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "22", "name": "CUSTOM BUILDS & RENTALS, LLC", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "23", "name": "Dumpster Dogs TX", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "24", "name": "Dynamic Fastener", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "25", "name": "ECUA Homes (Sand+Stabulizer)", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "26", "name": "Eloy Torres", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "27", "name": "Enrique Arteaga", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "28", "name": "Equadors Trucking Services", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "29", "name": "Fabco", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "30", "name": "Final Inspection 11/4/2024", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "31", "name": "Fire Sprinkler System", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "32", "name": "Fire Sprinkler Texas", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "33", "name": "Floor & Decor", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "34", "name": "Frank Gonzalez", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "35", "name": "Gabriel Pena", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "36", "name": "GC Rebar", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "37", "name": "Glavatec Inc.", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "38", "name": "GM Commercial Services", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "39", "name": "Gomez MGS (Moises Gomez)", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "40", "name": "Grainger", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "41", "name": "H2ECO Bulk LLC", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "42", "name": "HC Empire Drywall", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "43", "name": "Henry Osorto", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "44", "name": "Home Depot", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "45", "name": "Hunton AC Units Trane", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "46", "name": "Israel Figueroa", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "47", "name": "Jacore Fire Protection Co.", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "48", "name": "Jorge De Los Santos", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "49", "name": "Jose Ramirez", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "50", "name": "Juan F. Harnandez", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "51", "name": "Juan Molina", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "52", "name": "Juan Valadez", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "53", "name": "KES Landscaping LLC", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "54", "name": "L & G Equipment Rentals Inc.", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "55", "name": "Leon Plumbing", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "56", "name": "Lone Star Mapping LLC", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "57", "name": "Longhorn Texas Supply", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "58", "name": "LP Drilling, Texas City", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "59", "name": "Makmo Design LLC", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "60", "name": "MBCI", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "61", "name": "Norris Mechanical Services & More", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "62", "name": "Point Equipment Rental", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "63", "name": "Precision Concrete Pumping LLC", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "64", "name": "Pye Barker Fire & Safety", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "65", "name": "Quality Tles", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "66", "name": "Quick Waste", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "67", "name": "Red River Storm Water", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "68", "name": "Revels Brick Company Inc.", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "69", "name": "Reynaldo Benitez", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "70", "name": "Ricardo Rodriguez", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "71", "name": "Rodolfo Ladesma", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "72", "name": "Rodrigos Concrete Cuts & Cores", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "73", "name": "Roto Rooter", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "74", "name": "Sam's Club", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "75", "name": "Sandra Cruz", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "76", "name": "Sapo Engineering", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "77", "name": "Sherwin Williams", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "78", "name": "South Houston Concrete Pipe Co.", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "79", "name": "Stainless Kitchen & More", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "80", "name": "Strifes Air Conditioning & Heating", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "81", "name": "Sylvia Valadez", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "82", "name": "Tejas Materials, Inc.", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "83", "name": "Texas Contracting Consultants", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "84", "name": "Texas Shield Roofing LLC", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "85", "name": "Texcon Ready Mix Inc.", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "86", "name": "The Kings Transport", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "87", "name": "The Murillo Company", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "88", "name": "TO BE PAID", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "89", "name": "Triple S", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "90", "name": "Tulio Linares", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "91", "name": "Uinted Rentals", "contactPerson": "", "phone": "", "email": "", "trade": "" },
    { "id": "92", "name": "Victor Rodriguez", "contactPerson": "", "phone": "", "email": "", "trade": "" }
];

export const budgetCategories: BudgetCategory[] = [
    { "id": "1", "name": "Ansul System" },
    { "id": "2", "name": "Bollards/Car-stoppers" },
    { "id": "3", "name": "Builder's Risk" },
    { "id": "4", "name": "Cleanup" },
    { "id": "5", "name": "Curbs Labor" },
    { "id": "6", "name": "Curbs Material" },
    { "id": "7", "name": "Dirtwork Labor" },
    { "id": "8", "name": "Doors/Hardware Labor" },
    { "id": "9", "name": "Doors/Hardware Material" },
    { "id": "10", "name": "Electrical" },
    { "id": "11", "name": "Floor / Tiles Labor" },
    { "id": "12", "name": "Floor / Tiles Material" },
    { "id": "13", "name": "Foundation Labor" },
    { "id": "14", "name": "Foundation Material" },
    { "id": "15", "name": "Framing Labor" },
    { "id": "16", "name": "Framing Material" },
    { "id": "17", "name": "Haul Off" },
    { "id": "18", "name": "HVAC" },
    { "id": "19", "name": "Landscape Labor" },
    { "id": "20", "name": "Landscape Material" },
    { "id": "21", "name": "Millwork" },
    { "id": "22", "name": "Misc." },
    { "id": "23", "name": "Paint Labor" },
    { "id": "24", "name": "Paint Material" },
    { "id": "25", "name": "Parking Lot Labor" },
    { "id": "26", "name": "Parking Lot Material" },
    { "id": "27", "name": "Plumbing" },
    { "id": "28", "name": "Pollution Control Labor" },
    { "id": "29", "name": "Pollution Control Material" },
    { "id": "30", "name": "RENTALS" },
    { "id": "31", "name": "Roof/Coping/Downspots/CollectorBox" },
    { "id": "32", "name": "SideWalk Labor" },
    { "id": "33", "name": "SideWalk Material" },
    { "id": "34", "name": "Sitework Labor" },
    { "id": "35", "name": "Sitework Material" },
    { "id": "36", "name": "Steel Labor" },
    { "id": "37", "name": "Steel Material" },
    { "id": "38", "name": "Store front Canopy Labor" },
    { "id": "39", "name": "Store front Canopy Material" },
    { "id": "40", "name": "Store front GLASS" },
    { "id": "41", "name": "Stripes Labor" },
    { "id": "42", "name": "Stripes Material" },
    { "id": "43", "name": "Stucco/Bricks/Burnished Blocks" },
    { "id": "44", "name": "Survey" },
    { "id": "45", "name": "SWPP" },
    { "id": "46", "name": "VentHood" }
];

export const projects: Project[] = [];

export const tasks: Task[] = [];

export const rfis: RFI[] = [];

export const issues: Issue[] = [];

export const budgetItems: BudgetItem[] = [];

export const expenses: Expense[] = [];

export const changeOrders: ChangeOrder[] = [];
